--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PJZ9n/SimpleShop
build-by-default: true
branches:
  - master
projects:
  SimpleShop:
    path:
      libs:
        - src: dktapps-pm-pl/pmforms/pmforms
          version: 1.0.0
        - src: PJZ9n/MoneyConnector/MoneyConnector
          version: 1.1.0
...
